version: '3.8'

services:
  licener:
    build: .
    image: licener
    container_name: licener-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/licener
      - SESSION_SECRET=change_this_to_a_secure_random_string
      - JWT_SECRET=change_this_to_another_secure_random_string
    volumes:
      - licener-data:/usr/src/app/data
    depends_on:
      - mongo
    networks:
      - licener-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  mongo:
    image: mongo:6
    container_name: licener-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=licener
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - licener-network
    # Comment out the following lines if you want to expose MongoDB to the host
    # ports:
    #   - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  licener-data:
    name: licener-data
  mongo-data:
    name: licener-mongodb-data
  mongo-config:
    name: licener-mongodb-config

networks:
  licener-network:
    name: licener-network
    driver: bridge